Iter3
msjai/loyalty-service pull request #3
Opened 2023-02-14 11:25 UTC by msjai

2023-02-19 14:16 UTC, Bazys requested changes
Это конечно хитрый ход засунуть io.Reader в контекст.
Но давай не засовывать ВСЁ в контектс.
Максимум, на что я согласен это ID юзера в контексте

2023-02-19 14:16 UTC, Bazys commented on internal/controller/auth.go
> +	reader := ctx.Value(middleware.KeyReader).(io.Reader)
io.Reader в контекст!
это слишком

2023-02-20 08:30 UTC, msjai commented on internal/controller/auth.go
> +	reader := ctx.Value(middleware.KeyReader).(io.Reader)
исправил

2023-02-20 08:38 UTC, msjai commented on internal/controller/auth.go
> +func clearUserFields(user *entity.User) *entity.User {
исправил. Теперь функция не возвращает значение. Вообще мысл в том чтобы лишние поля если придут заполненными, чтобы их случайно не использовать. Типо доп. защита.

2023-02-20 08:40 UTC, msjai commented on internal/controller/auth.go
> +func clearUserFields(user *entity.User) *entity.User {
еще раз исправил, теперь структуру передаю по значению, что более оптимально. И дальше использую это значение.

2023-02-24 17:53 UTC, closed without merging